server:
  port: 8761 # Eureka -> Web Service Port

spring:
  application:
    name: discoveryservice # Micro Service ID

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # Eureka 는 Server 로서 기동하기 때문에, 자기 자신을 서비스로서 등록할 필요가 없기 때문에
    # 해당 설정을 꺼줌